---
title: "About"
output: 
  html_document
---

## Evaluation of Alternative Harvest Control Rules for New England Groundfish

<br>

<style>
div.blue{background-color:#e6f0ff; border-radius: 5px; padding: 10px; font-size:20px;}
</style>
<div class="blue">

Introduction:
</div>




Management of New England groundfish fisheries has been challenging due to the multispecies nature of the fishery and the varied status of stocks that ranges from historic low to record high biomasses. Additionally, most groundfish stock assessments exhibit inconsistencies among recent stock assessment estimates (a.k.a. retrospective patterns), which can present
challenges for sustainable management of fisheries. Accordingly, the New England Fishery Management Council (NEFMC) initiated a review of groundfish harvest control rules (HCRs) to improve the performance of fisheries management.
**The goal of this analysis was to evaluate the performance of alternative HCRs for New England groundfish stocks using management strategy evaluation (MSE).**



<br>



<style>
div.blue{background-color:#e6f0ff; border-radius: 5px; padding: 10px; font-size:20px;}
</style>
<div class="blue">

Approach:
</div>



This project focused on testing alternative HCR performance under a range of current groundfish conditions and stock assessment issues.<br>
  * **It did not test:**
      + all potential conditions and stock assessment issues contributing to the current state of groundfish stocks
      + determine optimal HCRs based on fishery goals because management goals need to be defined and prioritized first before optimal HCRs can be determined

This tool allows users to explore performance of HCRs through scenarios with different combinations of stock size, recruitment, and natural mortality assumptions as well as stock assessment model specifications for when a stock is overfished, not overfished, and when a stock assessment model has a misspecification and retrospective patterns. **Scenarios were structured based on these research questions:**

1. How do alternative HCRs perform when a stock is overfished? <br>
2. How do alternative HCRs perform when a stock is not overfished? <br>
3. How do alternative HCRs perform when there is a stock assessment misspecification and retrospective patterns? <br>
4. When retrospective patterns exist, do retrospective adjustments result in better performance than no retrospective adjustments?

<br>




<style>
div.blue{background-color:#e6f0ff; border-radius: 5px; padding: 10px; font-size:20px;}
</style>
<div class="blue">

How to use this tool:
</div>



There are five tabs across the top of the page designed to walk users through the results from the MSE. 
<br>

1. **Home:** Introduces the rationale, goals, approach of the project. This page also links to the full report, executive summary, and GMRI project site. Further down the page there are also tabs that explain the alternative HCRs, scenarios, and performance metrics in more detail. There are also glossary and acknowledgment tabs included here. <br>

2. **Stock Performance:** Results from the MSE pertaining to the stock are displayed here by choosing model specifications, clicking "create plots" and moving across the tabs to see different performance metrics comparing HCRs. <br>

3. **Assessment Performance:** Results from the MSE pertaining to the stock assessment are displayed here by choosing model specifications, clicking "create plots" and moving across the tabs to see different performance metrics comparing HCRs. <br>

4. **Management Performance:** Results from the MSE pertaining to the stock management are displayed here by choosing model specifications, clicking "create plots" and moving across the tabs to see different performance metrics comparing HCRs. <br>
    * **User specifies:** 
       + operating model (OM) and misspecification scenario 
       + rho-adjustment option
       + stock assessment frequency <br>
<br>

5. **Misspecifications:** Compare misspecifications based on guided prompts <br>
  * **User chooses to compare:**
      + Misspecified versus correctly specified stock assessment with             further choice of the type of misspecification
      + Rho-adjusted versus not rho-adjusted for the natural mortality and         recruitment misspecified scenario
      + Two-year versus annual stock assessment update frequency for the          natural mortality and recruitment misspecified scenario <br>
      
  * Natural mortality and recruitment misspecification used for               rho-adjustment and frequency comparisons because it is likely             multiple parameters are misspecified and the combination produced         retrospective patterns similar to those in the most recent GOM cod        stock assessment.

<br>

